fastscore:
  fleet:
    - api: model-manage
      host: host01
      port: 8002
    - api: engine
      host: host01
      port: 8003
    - api: engine
      host: host01
      port: 8004
    - api: engine
      host: host01
      port: 8005
    - api: engine
      host: host01
      port: 8006

  db:
    type: mysql
    host: host01
    port: 3306
    username: root
    password: root

  pneumo:
    type: kafka
    bootstrap:
      - host01:9092
    topic: notify
