version: '2'
services:
  dashboard:
    image: fastscore/dashboard:1.6.1
    network_mode: "bridge"
    ports:
        - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      CONNECT_PREFIX: https://172.17.0.1:8001

  connect:
    image: fastscore/connect:1.6.1
    network_mode: "bridge"
    ports:
        - "8001:8001"
    stdin_open: true
    tty: true

  engine-1:
    image: fastscore/engine:1.6.1
    network_mode: "bridge"
    ports:
        - "8003:8003"
    stdin_open: true
    tty: true
    volumes:
        - ./data:/root/data
    environment:
        CONNECT_PREFIX: https://172.17.0.1:8001

  engine-2:
    image: fastscore/engine:1.6.1
    network_mode: "bridge"
    ports:
        - "8004:8003"
    stdin_open: true
    tty: true
    volumes:
        - ./data:/root/data
    environment:
        CONNECT_PREFIX: https://172.17.0.1:8001

  engine-3:
    image: fastscore/engine:1.6.1
    network_mode: "bridge"
    ports:
        - "8005:8003"
    stdin_open: true
    tty: true
    environment:
        CONNECT_PREFIX: https://172.17.0.1:8001

  engine-4:
    image: fastscore/engine:1.6.1
    network_mode: "bridge"
    ports:
        - "8006:8003"
    stdin_open: true
    tty: true
    environment:
        CONNECT_PREFIX: https://172.17.0.1:8001

  database:
    image: fastscore/model-manage-mysql:1.6.1
    network_mode: "bridge"
    ports:
        - "3306:3306"

  model-manage:
    image: fastscore/model-manage:1.6.1
    network_mode: "bridge"
    ports:
        - "8002:8002"
    stdin_open: true
    tty: true
    depends_on:
      - connect
      - database
    environment:
      CONNECT_PREFIX: https://172.17.0.1:8001
